pipeline {

    environment {
        registry = "${IMAGE_NAME}"
        BUILD_NUMBER = "${BUILD_NUMBER}"

    }

    agent any

    options {
        skipDefaultCheckout(true)
    }
    stages {


        stage('Checkout (GitHub)') {
            steps{
                sh 'echo "Ok ok ok"'
            }
        }


    }
}